from sklearn.datasets import make_blobs
from sklearn.decomposition import PCA
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""
Principal Component Analysis (PCA)
----------------------------------
This script demonstrates dimensionality reduction using PCA on
synthetic data generated by make_blobs. It shows how PCA reduces
feature dimensions and explains variance contribution of each
principal component.
"""

# --------------------------------------------------
# 1. Generate synthetic dataset
# --------------------------------------------------
X, y = make_blobs(n_samples=100, n_features=10, random_state=0)

print("Before PCA:", X.shape)

# --------------------------------------------------
# 2. Apply PCA
# --------------------------------------------------
pca = PCA(n_components=4)
pca.fit(X)

X_reduced = pca.transform(X)

print("After PCA:", X_reduced.shape)
print("Number of components:", pca.n_components_)
print("Explained variance ratio:", pca.explained_variance_ratio_)

# --------------------------------------------------
# 3. Analyze explained variance
# --------------------------------------------------
df_variance = pd.DataFrame({
    "Principal Component": ["PC1", "PC2", "PC3", "PC4"],
    "Explained Variance Ratio": pca.explained_variance_ratio_
})

# --------------------------------------------------
# 4. Visualization
# --------------------------------------------------
sns.barplot(
    x="Principal Component",
    y="Explained Variance Ratio",
    data=df_variance,
    color="c"
)

plt.title("Explained Variance Ratio by Principal Components")
plt.show()
