import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.datasets import make_blobs

"""
K-Means Clustering Example
-------------------------
This script demonstrates K-Means clustering using synthetic data
generated by make_blobs. The workflow includes data generation,
model training, prediction, and visualization of cluster centroids.
"""

# --------------------------------------------------
# 1. Generate synthetic dataset
# --------------------------------------------------
X, y_true = make_blobs(
    n_samples=300,
    centers=4,
    cluster_std=0.5,
    random_state=0
)

X_test, _ = make_blobs(
    n_samples=10,
    centers=4,
    cluster_std=0.5,
    random_state=0
)

# --------------------------------------------------
# 2. Train K-Means model
# --------------------------------------------------
kmeans = KMeans(n_clusters=4)
kmeans.fit(X)

# --------------------------------------------------
# 3. Prediction
# --------------------------------------------------
y_pred = kmeans.predict(X)
y_pred_test = kmeans.predict(X_test)

# Cluster centers
centers = kmeans.cluster_centers_

# --------------------------------------------------
# 4. Visualization
# --------------------------------------------------
plt.scatter(X[:, 0], X[:, 1], c=y_pred, label="Training Data")
plt.scatter(
    X_test[:, 0],
    X_test[:, 1],
    c=y_pred_test,
    s=120,
    marker="x",
    label="Test Data"
)

# Plot centroids
plt.scatter(centers[0, 0], centers[0, 1], c="blue", label="Centroid 1")
plt.scatter(centers[1, 0], centers[1, 1], c="green", label="Centroid 2")
plt.scatter(centers[2, 0], centers[2, 1], c="red", label="Centroid 3")
plt.scatter(centers[3, 0], centers[3, 1], c="black", label="Centroid 4")

plt.legend(frameon=True)
plt.title("K-Means Clustering Result")
plt.show()
